ERP-1535 Proper tab-handling, proper handling of selection when user …
ActindoElements/actindo-date-picker pull request #3
Opened 2018-10-23 15:12 UTC by sdorheim

…changes the input-date. Allow empty min and max value. Added possibility to have empty values

2018-10-23 15:19 UTC, cdreisbach commented on actindo-date-picker.html
> +                return date && date.getTime && !isNaN(date.getTime());
date.getTime() - brackets missing

2018-10-24 12:41 UTC, dev756 requested changes

2018-10-24 12:41 UTC, joule162534 commented on actindo-date-picker.html
> +                        (me.value.valueOf() === 'string') && me.value.length === 0)) {
closing bracket at wrong position

2018-10-24 12:41 UTC, joule162534 commented on actindo-date-picker.html
> +                        (me.value.valueOf() === 'string') && me.value.length === 0)) {
.valueOf wrong use typeof

2018-10-24 13:01 UTC, dev756 approved these changes

2018-10-24 13:02 UTC, dev756 requested changes

2018-10-24 13:02 UTC, joule162534 commented on actindo-date-picker.html
> +                        (me.value.typeOf() === 'string' && me.value.length === 0)
typeof me.value

2018-11-06 14:13 UTC, merged